### ISSUE TITLE
IAP Metaissue Lang Learn

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/lang_learn#2]
For IAP, our main goal is to set up the infrastructure in the back end for storing pieces of text and converting it into something that can be used in the front end for an anagram and quiz. For the front end, we want to wire frame and create a working prototype of the anagram and quiz applications, with a stretch goal of having a flashcard generator.

- [x] Create models in the back end for storing Text, Students, Instructors, and Leaderboards. (Jason)
    - [x] Create Django API endpoints for adding new instances of text.
- [x] Anagram #3 
- [x] Quiz #4
- [x] Part of Speech parser #5
